[package]
name = "currency_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.9",features=["json"]}
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.132"
tokio = {version = "1.20.1", features = ["full"] } 
